// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQYWAIl2dv347pXsSutwDv9r-6RXPzxlI',
    authDomain: 'teachzone-67e27.firebaseapp.com',
    databaseURL:
        'https://teachzone-67e27-default-rtdb.europe-west1.firebasedatabase.app',
    projectId: 'teachzone-67e27',
    storageBucket: 'teachzone-67e27.firebasestorage.app',
    messagingSenderId: '1053600739184',
    appId: '1:1053600739184:web:7c4735a577bd03900629b5',
    measurementId: 'G-MZXC878Q3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQYWAIl2dv347pXsSutwDv9r-6RXPzxlI',
    appId: '1:1053600739184:android:bddd287c8913d58e0629b5',
    messagingSenderId: '1053600739184',
    projectId: 'teachzone-67e27',
    storageBucket: 'teachzone-67e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQYWAIl2dv347pXsSutwDv9r-6RXPzxlI',
    appId: '1:1053600739184:ios:bddd287c8913d58e0629b5',
    messagingSenderId: '1053600739184',
    projectId: 'teachzone-67e27',
    storageBucket: 'teachzone-67e27.firebasestorage.app',
    iosBundleId: 'com.example.teachzoneApp',
  );
}
