import '../models/subject_model.dart';

class TestData {
  static List<Subject> getSampleSubjects() {
    return [
      Subject(
        id: 'math_1',
        name: 'الرياضيات للصف الأول الثانوي',
        description: 'شرح كامل لمنهج الرياضيات للصف الأول الثانوي مع تمارين عملية وتطبيقات واقعية. يشمل الجبر والهندسة والإحصاء.',
        teacherId: 'teacher_ahmed',
        teacherName: 'أستاذ أحمد محمد',
        price: 200.0,
        rating: 4.8,
        imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
        categories: ['الرياضيات', 'الثانوي', 'منهج سعودي'],
        totalStudents: 150,
        createdAt: DateTime(2024, 1, 15),
        isFeatured: true,
      ),
      Subject(
        id: 'physics_1', 
        name: 'الفيزياء المتقدمة',
        description: 'دورة متقدمة في الفيزياء تشمل الميكانيكا والكهرباء والمغناطيسية. مع تجارب عملية وتطبيقات حياتية.',
        teacherId: 'teacher_sara',
        teacherName: 'د. سارة عبدالله',
        price: 300.0,
        rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400',
        categories: ['الفيزياء', 'الثانوي', 'منهج سعودي'],
        totalStudents: 89,
        createdAt: DateTime(2024, 1, 10),
        isFeatured: true,
      ),
      Subject(
        id: 'arabic_1',
        name: 'اللغة العربية - النحو والصرف',
        description: 'دورة شاملة في النحو والصرف للمرحلة الثانوية. تركيز على القواعد الأساسية والتطبيقات العملية.',
        teacherId: 'teacher_khalid',
        teacherName: 'أ. خالد إبراهيم',
        price: 150.0,
        rating: 4.7,
        imageUrl: 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?w=400',
        categories: ['اللغة العربية', 'الثانوي', 'منهج سعودي'],
        totalStudents: 203,
        createdAt: DateTime(2024, 1, 5),
        isFeatured: false,
      ),
      Subject(
        id: 'english_1',
        name: 'English Conversation Mastery',
        description: 'Master English conversation skills with native-like fluency. Focus on speaking, listening, and real-life situations.',
        teacherId: 'teacher_emily',
        teacherName: 'Ms. Emily Johnson',
        price: 250.0,
        rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=400',
        categories: ['اللغة الإنجليزية', 'الثانوي', 'منهج سعودي'],
        totalStudents: 178,
        createdAt: DateTime(2024, 1, 8),
        isFeatured: true,
      ),
      Subject(
        id: 'chemistry_1',
        name: 'الكيمياء العملية',
        description: 'تعلم الكيمياء من خلال التجارب العملية والتفاعلات الكيميائية. منهج تفاعلي وشيق.',
        teacherId: 'teacher_nora',
        teacherName: 'د. نورا أحمد',
        price: 220.0,
        rating: 4.6,
        imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400',
        categories: ['الكيمياء', 'الثانوي', 'منهج سعودي'],
        totalStudents: 95,
        createdAt: DateTime(2024, 1, 12),
        isFeatured: false,
      ),
      Subject(
        id: 'history_1',
        name: 'التاريخ الإسلامي',
        description: 'رحلة عبر التاريخ الإسلامي من عصر الرسالة إلى العصر الحديث. تحليل الأحداث والشخصيات المؤثرة.',
        teacherId: 'teacher_omar',
        teacherName: 'د. عمر الفاروق',
        price: 180.0,
        rating: 4.8,
        imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
        categories: ['التاريخ', 'الثانوي', 'منهج سعودي'],
        totalStudents: 134,
        createdAt: DateTime(2024, 1, 3),
        isFeatured: true,
      ),
      Subject(
        id: 'biology_1',
        name: 'علم الأحياء - الأحياء الدقيقة',
        description: 'استكشاف عالم الأحياء الدقيقة والخلية والوراثة. مع صور ومقاطع فيديو توضيحية.',
        teacherId: 'teacher_layla',
        teacherName: 'د. ليلى مصطفى',
        price: 210.0,
        rating: 4.7,
        imageUrl: 'https://images.unsplash.com/photo-1530026405186-1f621e6a1175?w=400',
        categories: ['الأحياء', 'الثانوي', 'منهج سعودي'],
        totalStudents: 112,
        createdAt: DateTime(2024, 1, 7),
        isFeatured: false,
      ),
      Subject(
        id: 'programming_1',
        name: 'برمجة Python للمبتدئين',
        description: 'تعلم أساسيات البرمجة بلغة Python من الصفر. مشاريع عملية وأمثلة حية.',
        teacherId: 'teacher_ali',
        teacherName: 'م. علي التميمي',
        price: 350.0,
        rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1526379879527-8559ecfcaec0?w=400',
        categories: ['البرمجة', 'مهارات', 'تقنية'],
        totalStudents: 267,
        createdAt: DateTime(2024, 1, 20),
        isFeatured: true,
      ),
    ];
  }

  static Map<String, dynamic> getSampleTeacherData() {
    return {
      'name': 'أستاذ أحمد محمد',
      'email': 'ahmed@teachzone.com',
      'specialization': 'الرياضيات والفيزياء',
      'experience': '10 سنوات',
      'rating': 4.8,
      'totalStudents': 450,
      'profileImage': '',
    };
  }

  static Map<String, dynamic> getSampleStudentData() {
    return {
      'name': 'محمد عبدالله',
      'email': 'mohamed@student.com', 
      'grade': 'أول ثانوي',
      'curriculum': 'منهج سعودي',
      'joinedAt': DateTime(2024, 1, 1),
      'profileImage': '',
    };
  }
}